//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RI.Claim.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineClaim
    {
        public int UID { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public string ClaimType { get; set; }
        public string ProductName { get; set; }
        public string Title { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string DriverPassportNumber { get; set; }
        public string DaytimeContactNo { get; set; }
        public string AfterHoursContactNo { get; set; }
        public string Email { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Suburb { get; set; }
        public string Postcode { get; set; }
        public string State { get; set; }
        public Nullable<bool> OtherClaimant { get; set; }
        public string RegularUserTitle { get; set; }
        public string RegularUserFirstname { get; set; }
        public string RegularUserSurname { get; set; }
        public Nullable<System.DateTime> RegularUserDateOfBirth { get; set; }
        public string RegularUserRelationship { get; set; }
        public Nullable<bool> RegularUserAuthorised { get; set; }
        public string RegularUserDriverPassportNumber { get; set; }
        public string InsuredMobileNumber { get; set; }
        public string InsuredIMEISerial { get; set; }
        public Nullable<bool> WarrantyRepair { get; set; }
        public string DeviceMakeModelColour { get; set; }
        public Nullable<System.DateTime> DateOfIncident { get; set; }
        public string IncidentLocation { get; set; }
        public string AustraliaOrOverseas { get; set; }
        public Nullable<System.DateTime> LastTimeDeviceSeen { get; set; }
        public string WhereWasDevice { get; set; }
        public string DetailedExplanation { get; set; }
        public string MobileNoWhenMissing { get; set; }
        public string TelcoNetwork { get; set; }
        public Nullable<bool> HasSIMCardBeenReplaced { get; set; }
        public Nullable<System.DateTime> SIMReplacedDateTime { get; set; }
        public string PoliceReferenceNumber { get; set; }
        public string TypeOfDamage { get; set; }
        public Nullable<bool> PowerOnWorking { get; set; }
        public Nullable<bool> DisplayWorking { get; set; }
        public Nullable<bool> ScreenDamaged { get; set; }
        public Nullable<bool> TouchWorking { get; set; }
        public Nullable<bool> BackGlassDamaged { get; set; }
        public Nullable<bool> RearCameraDamaged { get; set; }
        public Nullable<bool> EarphonesSpeakersWorking { get; set; }
        public Nullable<bool> ChargingPortDamaged { get; set; }
        public Nullable<bool> PreviousLiquidDamage { get; set; }
        public string MobileNoInDeviceAtTimeOfDamage { get; set; }
        public Nullable<bool> DeclarationOfTruth { get; set; }
        public string ClaimantPhoto { get; set; }
        public string RegularUserPhoto { get; set; }
        public string IMEIAttachedFilename { get; set; }
        public string FullName { get; set; }
        public string StateAbbv { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateRealisedMissing { get; set; }
        public string LocationRealisedMissing { get; set; }
        public Nullable<bool> NeedToPull { get; set; }
        public string PayLoad { get; set; }
        public Nullable<bool> IsManualUpload { get; set; }
    }
}
