//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RI.Claim.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RiskVHAEntities : DbContext
    {
        public RiskVHAEntities()
            : base("name=RiskVHAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Supplier> t_Supplier { get; set; }
        public virtual DbSet<tblPhone2> tblPhone2 { get; set; }
        public virtual DbSet<tblScheme> tblSchemes { get; set; }
        public virtual DbSet<tblClaim> tblClaims { get; set; }
        public virtual DbSet<tblPhone> tblPhones { get; set; }
        public virtual DbSet<tblClaimNote> tblClaimNotes { get; set; }
        public virtual DbSet<OnlineClaim> OnlineClaims { get; set; }
    
        public virtual ObjectResult<string> GetClaimNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetClaimNumber");
        }
    
        public virtual ObjectResult<string> NewClaim()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("NewClaim");
        }
    }
}
