//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RI.Claim.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Supplier()
        {
            this.tblSchemes = new HashSet<tblScheme>();
            this.tblClaims = new HashSet<tblClaim>();
        }
    
        public int sup_id { get; set; }
        public string sup_Name { get; set; }
        public Nullable<int> sup_ReplacementPhoneSchemeId { get; set; }
        public Nullable<int> sup_ReplacementSIMCardSchemeId { get; set; }
        public Nullable<bool> Keep { get; set; }
        public Nullable<decimal> Sup_SimCardPrice { get; set; }
        public Nullable<decimal> Sup_FreightPhoneSim { get; set; }
        public Nullable<decimal> Sup_FreightPhoneOnly { get; set; }
        public Nullable<decimal> Sup_FreightSimOnly { get; set; }
        public Nullable<bool> Output { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblScheme> tblSchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaim> tblClaims { get; set; }
    }
}
