//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RI.Claim.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClaim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClaim()
        {
            this.tblClaimNotes = new HashSet<tblClaimNote>();
        }
    
        public string ClaimNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LodgedDate { get; set; }
        public Nullable<bool> AfterHoursFlag { get; set; }
        public string NESLodger { get; set; }
        public Nullable<bool> InformationConsentFlag { get; set; }
        public Nullable<int> SchemeID { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string IMEINumber { get; set; }
        public string NewIMEINumber { get; set; }
        public Nullable<System.DateTime> cla_IMEIDate { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
        public string CompanyName { get; set; }
        public string FamilyName { get; set; }
        public string GivenName { get; set; }
        public string Title { get; set; }
        public string AccountNumber { get; set; }
        public string cla_LodgerLastName { get; set; }
        public string cla_LodgerFirstName { get; set; }
        public string cla_LodgerRelationship { get; set; }
        public string LastPersonGivenName { get; set; }
        public string LastPersonFamilyName { get; set; }
        public string ContactNumber { get; set; }
        public string ContactNumber2 { get; set; }
        public string PostalAddress1 { get; set; }
        public string PostalAddress2 { get; set; }
        public string PostalSuburb { get; set; }
        public string PostalPostcode { get; set; }
        public string PhoneDealer { get; set; }
        public string Suburb { get; set; }
        public string PhoneDealelPostCode { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> LossDate { get; set; }
        public string DamageType { get; set; }
        public string LossType { get; set; }
        public Nullable<bool> PreviousClaimFlag { get; set; }
        public Nullable<System.DateTime> PreviousClaimDate { get; set; }
        public Nullable<bool> CancelInsuranceFlag { get; set; }
        public Nullable<bool> SimCardFlag { get; set; }
        public string cla_SimCardType { get; set; }
        public string cla_SimCardNumber { get; set; }
        public Nullable<bool> cla_SimCardPreviousFlag { get; set; }
        public Nullable<decimal> AccLeatherCase { get; set; }
        public Nullable<decimal> AccHandsFree { get; set; }
        public Nullable<decimal> AccOther { get; set; }
        public string AccOtherDescr { get; set; }
        public Nullable<bool> PoliceReportFlag { get; set; }
        public string PoliceReportNumber { get; set; }
        public Nullable<bool> cla_UnattendedPublic { get; set; }
        public Nullable<bool> cla_UnattendedIntentional { get; set; }
        public Nullable<bool> cla_UnattendedVehicle { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserID { get; set; }
        public decimal Excess { get; set; }
        public Nullable<decimal> UnauthorisedCalls { get; set; }
        public Nullable<decimal> GST { get; set; }
        public string RepairReplaceCashIndicator { get; set; }
        public Nullable<int> CurrentPhoneID { get; set; }
        public Nullable<int> ReplacePhoneID { get; set; }
        public Nullable<decimal> ReplaceCost { get; set; }
        public Nullable<decimal> ReplaceVarianceCost { get; set; }
        public Nullable<decimal> SimcardCost { get; set; }
        public string cla_FreightCostType { get; set; }
        public Nullable<decimal> FreightCost { get; set; }
        public string Repairer { get; set; }
        public Nullable<decimal> RepairCost { get; set; }
        public Nullable<decimal> AssessmentCost { get; set; }
        public Nullable<decimal> CashCost { get; set; }
        public string DeliveryAddress1 { get; set; }
        public string DeliveryAddress2 { get; set; }
        public string DeliverySuburb { get; set; }
        public string DeliveryPostcode { get; set; }
        public Nullable<bool> CorrectInfoFlag { get; set; }
        public Nullable<System.DateTime> MoreInfoStatusDate { get; set; }
        public string MoreInfoUserid { get; set; }
        public string cla_InvoiceNo1 { get; set; }
        public string cla_InvoiceNo2 { get; set; }
        public Nullable<System.DateTime> ApprovedStatusDate { get; set; }
        public string ApprovedUserid { get; set; }
        public Nullable<System.DateTime> PaidStatusDate { get; set; }
        public string PaidUserid { get; set; }
        public string cla_PaidFull { get; set; }
        public string cla_PaidBalance { get; set; }
        public Nullable<System.DateTime> DeclinedStatusDate { get; set; }
        public string DeclinedUserid { get; set; }
        public Nullable<System.DateTime> CancelledStatusDate { get; set; }
        public string CancelledUserid { get; set; }
        public string CCName { get; set; }
        public string CCNumber { get; set; }
        public string CCExpiryMonthYear { get; set; }
        public Nullable<decimal> TotalClaimCost { get; set; }
        public Nullable<decimal> TotalCostLessGST { get; set; }
        public string DiaryEntry { get; set; }
        public Nullable<System.DateTime> DiaryDate { get; set; }
        public Nullable<bool> GSTRegisteredFlag { get; set; }
        public Nullable<float> InputTaxCredit { get; set; }
        public string ABN { get; set; }
        public Nullable<bool> cla_AuthoriseExcess { get; set; }
        public string cla_DeliverPerson { get; set; }
        public string cla_DeliverPersonLicense { get; set; }
        public string cla_PostalState { get; set; }
        public string cla_PhoneDealerState { get; set; }
        public string cla_PhoneAccessoriesPaidTo { get; set; }
        public Nullable<decimal> cla_PhoneAccessoriesInvoiceNo1Amt { get; set; }
        public Nullable<decimal> cla_PhoneAccessoriesInvoiceNo2Amt { get; set; }
        public string cla_PhoneAccessoriesInvoiceNo3 { get; set; }
        public Nullable<decimal> cla_PhoneAccessoriesInvoiceNo3Amt { get; set; }
        public string cla_PhoneAccessoriesInvoiceNo4 { get; set; }
        public Nullable<decimal> cla_PhoneAccessoriesInvoiceNo4Amt { get; set; }
        public string cla_PhoneAccessoriesInvoiceNo5 { get; set; }
        public Nullable<decimal> cla_PhoneAccessoriesInvoiceNo5Amt { get; set; }
        public string cla_PhoneAccessoriesInvoiceNo6 { get; set; }
        public Nullable<decimal> cla_PhoneAccessoriesInvoiceNo6Amt { get; set; }
        public string cla_SimCardPaidTo { get; set; }
        public Nullable<System.DateTime> cla_SimCardPaidToDate { get; set; }
        public string cla_SimCardInvoiceNo1 { get; set; }
        public Nullable<decimal> cla_SimCardInvoiceNo1Amt { get; set; }
        public string cla_RepairerPaidTo { get; set; }
        public Nullable<System.DateTime> cla_RepairerPaidToDate { get; set; }
        public string cla_RepairerInvoiceNo1 { get; set; }
        public Nullable<decimal> cla_RepairerInvoiceNo1Amt { get; set; }
        public string cla_RepairerInvoiceNo2 { get; set; }
        public Nullable<decimal> cla_RepairerInvoiceNo2Amt { get; set; }
        public string cla_RepairerInvoiceNo3 { get; set; }
        public Nullable<decimal> cla_RepairerInvoiceNo3Amt { get; set; }
        public string cla_OtherPaidTo { get; set; }
        public Nullable<System.DateTime> cla_OtherPaidToDate { get; set; }
        public string cla_OtherInvoiceNo1 { get; set; }
        public Nullable<decimal> cla_OtherInvoiceNo1Amt { get; set; }
        public string cla_OtherInvoiceNo2 { get; set; }
        public Nullable<decimal> cla_OtherInvoiceNo2Amt { get; set; }
        public string cla_OtherInvoiceNo3 { get; set; }
        public Nullable<decimal> cla_OtherInvoiceNo3Amt { get; set; }
        public string cla_AccProductCode { get; set; }
        public string cla_AccOtherProductCode { get; set; }
        public string cla_RepairerJobNo { get; set; }
        public Nullable<decimal> cla_ShortfallUpgradeCost { get; set; }
        public string cla_DeliveryState { get; set; }
        public string CCExpiryYear { get; set; }
        public Nullable<System.DateTime> cla_CCDateEntered { get; set; }
        public Nullable<decimal> cla_CCAmount { get; set; }
        public Nullable<bool> cla_LodgerHasAuthority { get; set; }
        public Nullable<bool> cla_LodgerAccountHolderNoEnglish { get; set; }
        public Nullable<bool> cla_DoNotOrder { get; set; }
        public int cla_BPayNumberSeed { get; set; }
        public string cla_BPayNumber { get; set; }
        public Nullable<bool> cla_BPayRequired { get; set; }
        public string cla_RepairReceiptNo { get; set; }
        public string cla_RepairConsignmentNo { get; set; }
        public Nullable<decimal> cla_OutstandingAmount { get; set; }
        public string cla_PhoneAccessoriesPaidTo2 { get; set; }
        public Nullable<System.DateTime> cla_PhoneAccessoriesPaidDate2 { get; set; }
        public string cla_PhoneAccessoriesPaidTo3 { get; set; }
        public Nullable<System.DateTime> cla_PhoneAccessoriesPaidDate3 { get; set; }
        public string cla_PhoneAccessoriesPaidTo4 { get; set; }
        public Nullable<System.DateTime> cla_PhoneAccessoriesPaidDate4 { get; set; }
        public string cla_RepairerPaidTo2 { get; set; }
        public Nullable<System.DateTime> cla_RepairerPaidToDate2 { get; set; }
        public string cla_OtherPaidTo2 { get; set; }
        public Nullable<System.DateTime> cla_OtherPaidToDate2 { get; set; }
        public Nullable<int> cla_ReplacePhone_sup_id { get; set; }
        public Nullable<int> cla_ReplaceSIMCard_sup_id { get; set; }
        public Nullable<int> cla_ReplaceSimCardID { get; set; }
        public string cla_ReplacePhone_SuppliersCode { get; set; }
        public string cla_ReplaceSIMCard_SuppliersCode { get; set; }
        public string cla_InsuranceType { get; set; }
        public string cla_TerminalId { get; set; }
        public Nullable<System.DateTime> cla_DateReportedToSP { get; set; }
        public Nullable<bool> cla_ProofOfForcibleEntry { get; set; }
        public Nullable<decimal> cla_ReplacePhoneRRP { get; set; }
        public Nullable<bool> cla_IMEIBlocked { get; set; }
        public string cla_DeclineReason { get; set; }
        public Nullable<bool> cla_ProofOfPurchase { get; set; }
        public string cla_IMEINotBlockedReason { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> CPHID_MIA { get; set; }
        public Nullable<int> RPHID_MIA { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<System.DateTime> LetterRec_IMEI { get; set; }
        public Nullable<System.DateTime> LetterRec_Damaged { get; set; }
        public Nullable<decimal> CashSettleAmount { get; set; }
        public string FaxNumber { get; set; }
        public string oSupplierName { get; set; }
        public Nullable<bool> oUseSupplier { get; set; }
        public string oPhone { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<System.DateTime> letterRec_IPhoneDamage { get; set; }
        public string WarningNote { get; set; }
        public string CaseManager { get; set; }
        public Nullable<bool> PhotoIDReceived { get; set; }
        public Nullable<bool> BillReceived { get; set; }
        public Nullable<bool> InteractionNotesReceived { get; set; }
        public Nullable<System.DateTime> DateTimeSimReplaced { get; set; }
        public Nullable<System.DateTime> ExcessPaidStatusDate { get; set; }
        public Nullable<System.DateTime> RepairerPaidStatusDate { get; set; }
        public Nullable<System.DateTime> CancelInsuranceDate { get; set; }
        public Nullable<bool> VHAInvolve { get; set; }
        public string CurrentUser { get; set; }
        public string VHACAPIN { get; set; }
        public string BAN { get; set; }
        public Nullable<bool> SimRequired { get; set; }
        public string ClaimType { get; set; }
        public string cla_ClosedReason { get; set; }
        public string PolicyNumber { get; set; }
        public string ApprovedClaimType { get; set; }
        public Nullable<int> OnLineClaimID { get; set; }
        public string ServiceType { get; set; }
    
        public virtual t_Supplier t_Supplier { get; set; }
        public virtual tblPhone2 tblPhone2 { get; set; }
        public virtual tblPhone2 tblPhone21 { get; set; }
        public virtual tblScheme tblScheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaimNote> tblClaimNotes { get; set; }
    }
}
