//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RI.Claim.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhone
    {
        public int PhoneID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string MakersCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserID { get; set; }
        public string ImportColour { get; set; }
        public string ImportModel { get; set; }
    }
}
