//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RI.Claim.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblScheme()
        {
            this.tblClaims = new HashSet<tblClaim>();
        }
    
        public int SchemeID { get; set; }
        public string SchemeName { get; set; }
        public Nullable<decimal> SimCardPrice { get; set; }
        public Nullable<decimal> FreightPhoneSim { get; set; }
        public Nullable<decimal> FreightPhoneOnly { get; set; }
        public Nullable<decimal> FreightSimOnly { get; set; }
        public string UpdateDate { get; set; }
        public string UpdateUserID { get; set; }
        public string Country { get; set; }
        public Nullable<int> sch_sup_id { get; set; }
        public Nullable<bool> Keep { get; set; }
        public Nullable<bool> Output { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual t_Supplier t_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClaim> tblClaims { get; set; }
    }
}
